### ISSUE TITLE
include directive does not work

### ISSUE THREAD

**Issue by wonyongc** [catppuccin/i3#2]
Per i3 user's guide (https://i3wm.org/docs/userguide.html#include)

```
Variables are shared between all config files, but beware of the following limitation:

    You can define a variable and use it within an included file.

    You cannot use (in the parent file) a variable that was defined within an included file.

```

Recommend changing the install instructions to avoid confusion.

**Comment by rubyowo** [comment]
thanks! mind creating a PR?

**Comment by rubyowo** [comment]
linking the manual would probably enough though.

**Comment by radek-stasta** [comment]
Yes, same here. Included variables don't work

**Comment by rubyowo** [comment]
Mentioned this in the README in [2032a2c](https://github.com/catppuccin/i3/commit/2032a2cb9ca063d797d19d039cfd5ed6eb332a55)
